title: "Marta Mainetti"
description: "Biostatistics & Data Science"
url: "https://username.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-seo-tag